version: '3'
services:
  ignite-server:
    build: ./ignite-server
    environment:
      JAVA_OPTS: -Xmx128m

  ignite-client:
    build: ./ignite-client
    links:
      - "ignite-server"
    environment:
      JAVA_OPTS: -Xmx128m

networks:
  service1_net:
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/16