spring:
  datasource:
    #    url: jdbc:mysql://database:3306/pjiangtutorial-local-mysql?useUnicode:true&characterEncoding:utf8
    url: jdbc:mysql://localhost:3306/test?useUnicode:true&characterEncoding:utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8080


  
  